---
# Necessary to be able to create folders inside.
- name: Temporarily enable inheritance on data dir
  win_acl_inheritance:
    path:   '{{ beacon_node_data_path }}'
    state:  'present'

- name: Create service folders
  win_file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ beacon_node_service_path }}'
    - '{{ beacon_node_era_dir_path }}'
    - '{{ beacon_node_secrets_path }}'
    - '{{ beacon_node_validators_path }}'
    - '{{ beacon_node_service_logs_path }}'
    - '{{ beacon_node_service_bin_path }}'
    - '{{ beacon_node_data_path }}'

- name: Fix service folder permissions
  win_owner:
    path: '{{ beacon_node_service_path }}'
    user: '{{ beacon_node_service_user_name }}'

- name: Disable inheritance on data dir
  win_acl_inheritance:
    path:   '{{ beacon_node_data_path }}'
    state:  'absent'

- name: Fix data folder ownership
  win_acl:
    path:    '{{ beacon_node_data_path }}'
    user:    '{{ beacon_node_service_user_name }}'
    rights:  'FullControl'
    inherit: 'ContainerInherit, ObjectInherit'
    type:    'allow'

- name: Create JWT secret file (optional)
  when: beacon_node_web3_jwt_secret is defined
  copy:
    dest:    '{{ beacon_node_web3_jwt_secret_path }}'
    content: '{{ beacon_node_web3_jwt_secret }}'

- name: Fix JWT secret file permissions
  when: beacon_node_web3_jwt_secret is defined
  win_owner:
    path: '{{ beacon_node_web3_jwt_secret_path }}'
    user: '{{ beacon_node_service_user_name }}'
