---
- name: Install GCC to compile Nim
  win_shell: 'scoop install --global gcc'

- name: Add GCC to the system wide PATH
  win_path:
    name: 'PATH'
    elements: 'C:\ProgramData\scoop\apps\gcc\current\bin'
    scope: 'machine'
    state: 'present'
  register: machine_path

- name: Restart host for PATH change to work
  win_reboot:
    reboot_timeout: 160
  when: machine_path.changed
