---
- name: Install MinGW-Nuwen and CMake to compile Nim
  win_shell: 'scoop install --global mingw-nuwen gcc cmake'

- name: Add GCC to the system wide PATH
  win_path:
    name: 'PATH'
    elements:
      - 'C:\ProgramData\scoop\apps\mingw-nuwen\current\bin'
      - 'C:\ProgramData\scoop\apps\gcc\current\bin'
    scope: 'machine'
    state: 'present'
  register: machine_path

- name: Set CC variable to fix builds
  win_path:
    name: 'CC'
    elements: 'gcc'
    scope: 'machine'
    state: 'present'
  register: machine_cc

- name: Restart host for PATH change to work
  win_reboot:
    reboot_timeout: 160
  when: machine_path.changed or machine_cc.changed
