---
- name: Create service folders
  win_file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ beacon_node_service_path }}'
    - '{{ beacon_node_service_logs_path }}'
    - '{{ beacon_node_service_bin_path }}'
    - '{{ beacon_node_data_path }}'

- name: Fix service folder permissions
  win_owner:
    path: '{{ beacon_node_service_path }}'
    user: '{{ beacon_node_service_user_name }}'

- name: Disable inheritance on data dir
  win_acl_inheritance:
    path:   '{{ beacon_node_data_path }}'
    state:  'absent'

- name: Fix data folder ownership
  win_acl:
    path:    '{{ beacon_node_data_path }}'
    user:    '{{ beacon_node_service_user_name }}'
    rights:  'FullControl'
    inherit: 'ContainerInherit, ObjectInherit'
    type:    'allow'

- name: Clone Git repository
  win_shell: |
    git --no-pager clone \
      {{ beacon_node_repo_url }} \
      {{ beacon_node_repo_path }} \
      --branch {{ beacon_node_repo_branch }}
  args:
    creates: '{{ beacon_node_repo_path }}'

- name: Update Git repo branch
  win_shell: |
    git checkout --force {{ beacon_node_repo_branch }}
  args:
    chdir: '{{ beacon_node_repo_path }}'

- name: Fix repo permissions
  win_owner:
    path: '{{ beacon_node_repo_path }}'
    user: '{{ beacon_node_service_user_name }}'

- name: Install GCC to compile Nim
  win_shell: 'scoop install --global gcc'

- name: Add GCC to the system wide PATH
  win_path:
    name: 'PATH'
    elements: 'C:\ProgramData\scoop\apps\gcc\current\bin'
    scope: 'machine'
    state: 'present'
  register: machine_path

- name: Restart host for PATH change to work
  win_reboot:
    reboot_timeout: 160
  when: machine_path.changed
