---
- name: Create windows service
  include_role: name=infra-role-winsw
  vars:
    winsw_service_id: '{{ beacon_node_service_name }}'
    winsw_service_name: 'Beacon Node {{ beacon_node_network }} ({{ beacon_node_repo_branch }})'
    winsw_service_description: 'Nimbus Eth2 Beacon Node'
    winsw_service_user: 'nimbus'
    winsw_service_logon_enabled: true
    winsw_service_logon_domain: '{{ ansible_netbios_name }}'
    winsw_service_logon_pass: '{{ beacon_node_service_user_pass }}'
    winsw_service_exe_path: '{{ beacon_node_service_exe }}'
    winsw_service_arguments: |
      --network={{ beacon_node_network }}
      --data-dir={{ beacon_node_data_path }}/shared_{{ beacon_node_network }}_0'
      {% for url in beacon_node_web3_urls | mandatory %}
      --web3-url={{ url | mandatory }}
      {% endfor %}
      --nat=extip:{{ beacon_node_public_address }}
      --log-level={{ beacon_node_log_level }}
      --log-file={{ beacon_node_service_path }}/log/nimbus.log
      --tcp-port={{ beacon_node_listening_port }}
      --udp-port={{ beacon_node_discovery_port }}
      --max-peers={{ beacon_node_max_peers }}
      --slashing-db-kind={{ beacon_node_slashing_db_kind }}
      --insecure-netkey-password=true
      --subscribe-all-subnets={{ beacon_node_subscribe_all | to_json }}
      --doppelganger-detection={{ beacon_node_doppelganger_detection | to_json }}
      --rpc
      --rpc-address=0.0.0.0
      --rpc-port={{ beacon_node_rpc_port }}
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port={{ beacon_node_metrics_port }}
