---
- name: Create windows service
  include_role: name=infra-role-winsw
  vars:
    winsw_service_name: 'Beacon Node {{ beacon_node_network }} ({{ beacon_node_repo_branch }})'
    winsw_service_description: 'Nimbus Eth2 Beacon Node running on {{ beacon_node_network }} network using {{ beacon_node_repo_branch }} branch.'
    winsw_service_id:           '{{ beacon_node_service_name }}'
    winsw_service_path:         '{{ beacon_node_service_path }}'
    winsw_service_user:         '{{ beacon_node_user }}'
    winsw_service_restart:      '{{ beacon_node_config_file.changed }}'
    winsw_service_logon_domain: '{{ ansible_netbios_name }}'
    winsw_service_logon_pass:   '{{ beacon_node_service_user_pass }}'
    winsw_service_logon_enabled: true
    winsw_service_log_size: 1024000
    winsw_service_log_keep: 10
    winsw_service_log_stderr_disabled: true
    winsw_service_exe_path: |
      {{ beacon_node_binary_path }}
    winsw_service_arguments: |
      --config-file={{ beacon_node_config_file_path }}
      {% if beacon_node_suggested_fee_recipient is defined %}
      --suggested-fee-recipient={{ beacon_node_suggested_fee_recipient | mandatory }}
      {% endif %}

# You can do it using Get-Service or 'sc qc'.
- name: Grant user ability to manage service
  register: wat
  win_shell: |
    Install-Module -Confirm Carbon
    Import-Module Carbon
    Grant-ServicePermission -Name "{{ beacon_node_service_name }}" `
      -Identity "{{ beacon_node_user }}" `
      -Start -Stop -QueryConfig -QueryStatus -EnumerateDependents -ReadControl
