---
- name: Create windows service
  include_role: name=infra-role-winsw
  vars:
    winsw_service_id: '{{ beacon_node_service_name }}'
    winsw_service_name: 'Beacon Node {{ beacon_node_network }} ({{ beacon_node_repo_branch }})'
    winsw_service_description: 'Nimbus Eth2 Beacon Node running on {{ beacon_node_network }} network using {{ beacon_node_repo_branch }} branch.'
    winsw_service_user: 'nimbus'
    winsw_service_logon_enabled: true
    winsw_service_logon_domain: '{{ ansible_netbios_name }}'
    winsw_service_logon_pass: '{{ beacon_node_service_user_pass }}'
    winsw_service_log_size: 1024000
    winsw_service_log_keep: 10
    winsw_service_log_stderr_disabled: true
    winsw_service_exe_path: '{{ beacon_node_service_exe }}'
    winsw_service_arguments: |
      --non-interactive
      --network={{ beacon_node_network }}
      --data-dir="{{ beacon_node_data_path }}\{{ beacon_node_data_folder }}"
      {% for url in beacon_node_web3_urls | mandatory %}
      --web3-url={{ url | mandatory }}
      {% endfor %}
      {% if beacon_node_validators_dir != "" %}
      --validators-dir="{{ beacon_node_validators_dir }}"
      {% endif %}
      {% if beacon_node_secrets_dir != "" %}
      --secrets-dir="{{ beacon_node_secrets_dir }}"
      {% endif %}
      --log-format={{ beacon_node_log_format }}
      --log-level={{ beacon_node_log_level }}
      --nat=extip:{{ beacon_node_public_address }}
      --tcp-port={{ beacon_node_listening_port }}
      --udp-port={{ beacon_node_discovery_port }}
      --max-peers={{ beacon_node_max_peers }}
      --num-threads={{ beacon_node_threads }}
      --slashing-db-kind={{ beacon_node_slashing_db_kind }}
      --insecure-netkey-password=true
      --subscribe-all-subnets={{ beacon_node_subscribe_all | to_json }}
      --doppelganger-detection={{ beacon_node_doppelganger_detection | to_json }}
      --rpc={{ beacon_node_rpc_enabled | to_json }}
      {% if beacon_node_rpc_enabled %}
      --rpc-address={{ beacon_node_rpc_address }}
      --rpc-port={{ beacon_node_rpc_port }}
      {% endif %}
      --rest={{ beacon_node_rest_enabled | to_json }}
      {% if beacon_node_rest_enabled %}
      --rest-address={{ beacon_node_rest_address }}
      --rest-port={{ beacon_node_rest_port }}
      {% endif %}
      --metrics={{ beacon_node_metrics_enabled | to_json }}
      {% if beacon_node_metrics_enabled %}
      --metrics-address={{ beacon_node_metrics_address }}
      --metrics-port={{ beacon_node_metrics_port }}
      {% endif %}
